# Generated by Django 6.1 on 2026-08-27 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congregants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'Families'},
        ),
    ]
